name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install scikit-learn

    - name: Run classification script
      run: python iris_classification.py

    - name: Run test script
      run: python iris_classification_test.py
