name: CML

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pandas
        pip install scikit-learn
        pip install numpy
        pip install matplotlib

    - name: Run script
      run: python iris_classification_plt.py

    - name: Create report
      run: |
        echo "## Metrics"
        cat metrics.txt
        echo "## Confusion matrix"
        cat plot.png
