on:
  push:
    branches:
      - Random_forest_plt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pandas
          pip install scikit-learn
          pip install numpy
          pip install matplotlib

      - name: Run iris_classification_plt.py
        run: python iris_classification_plt.py

      - name: Commit and push changes
        run: |
          git config --local user.email "vietrov-vlad@mail.ru"
          git config --local user.name "Demikello"
          git add .
          git commit -m "Add metrics and images"
          git push

      - name: Generate CML report
        uses: actions/checkout@v2
        with:
          repository: "cml-actions/report"
          path: .cml
        env:
          CML_REPORT_NAME: "Iris Classification Report"
          CML_REPORT_TITLE: "Metrics and Confusion Matrix"
          CML_REPORT_FILES: |
            plot.png
          CML_REPORT_STATUS: success
