name: CML

on: [pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pandas
          pip install scikit-learn
          pip install numpy
          pip install matplotlib

    - name: Run script
      run: python iris_classification_plt.py

    - name: Upload metrics and images
      uses: actions/upload-artifact@v2
      with:
        name: ml_report
        path: |
          ml_report.txt
          plot.png

