name: CML
on:
  push:
    branches:
      - Random_forest_plt
  pull_request:
    branches:
      - Random_forest_plt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pandas
          pip install scikit-learn
          pip install numpy
          pip install matplotlib

      - name: Create report
        run: |
          mkdir -p report
          cp images/*.png report/
          cp iris_classification_plt.py report/
          echo "Accuracy: ${{ steps.build.outputs.accuracy }}" >> report/metrics.txt
          echo "Confusion matrix: ${{ steps.build.outputs.confusion  }}" >> report/metrics.txt

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: classification_metrics_report
          path: report
