name: CML
on:
  push:
    branches:
      - Random_forest_plt
  pull_request:
    branches:
      - Random_forest_plt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script and generate report
        run: |
          python script.py > report.txt
          echo "::set-output name=report::report.txt"

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: classification_report
          path: report.txt
