name: CML
on:
  push:
    branches:
      - Random_forest_plt
  pull_request:
    branches:
      - Random_forest_plt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            pip install pandas
            pip install scikit-learn
            pip install numpy
            pip install matplotlib

      - name: Install CML
        run: |
            curl -s https://cml.dev/install.sh | sh

      - name: Run script and generate report
        run: python iris_classification_plt.py
        
      - name: Comment with metrics and images
        run: |
          cml comment create --report-metrics metrics.txt --report-charts images.zip
          cml send-comment comment.md
