name: CML
on:
  push:
    branches:
      - Random_forest_plt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v2

    - name: 'Run Python Script for Model Evaluation'
      run: |
        pip install pandas
        pip install scikit-learn
        pip install numpy
        pip install matplotlib  
        python iris_classification_plt.py

    - name: 'Set Up CML Environment'
      uses: iterative/setup-cml@v1
          
    - name: 'Generate CML Report'
      env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        echo "![ConfusionMatrix](plot.png)" >> report.md
        echo '### Metrics' >> report.md
        cat metrics.txt >> report.md 
        cml-publish plot.png --md >> report.md
        cml-send-comment report.md
