name: CML

on:
  pull_request:
    branches: Random_forest_plt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pandas
          pip install scikit-learn
          pip install numpy
          pip install matplotlib

      - name: Run script and generate report
        run: |
          python iris_classification_plt.py
      
      - name: Upload report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Report
          path: https://github.com/Demikello/Lab_3/pull/4
